@DOMAIN = http://localhost:3001

###
POST {{DOMAIN}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbWFuaHRoYW81OEBnbWFpbC5jb20iLCJpYXQiOjE2OTM4ODE5MzYsImV4cCI6MTY5NDQ4NjczNn0.gzA5uljlDVEguYZGYSxYW5u5X8iC9lkraFb3W2ZVNPg

{
    "email":"nhat4@gmail.com",
    "password":"1234587"
}
###
DELETE  {{DOMAIN}}/users/64f6a3a07b0a48b95e5919f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbWFuaHRoYW81OEBnbWFpbC5jb20iLCJpYXQiOjE2OTM4ODE5MzYsImV4cCI6MTY5NDQ4NjczNn0.gzA5uljlDVEguYZGYSxYW5u5X8iC9lkraFb3W2ZVNPg

