export const usersToSeed = [
  {
    _id: null,
    uid: '1',
    email: 'user1@example.com',
    password: 'password1',
    nick_name: 'User One',
    age: '25',
    gender: 'Male',
    avatar: 'https://example.com/avatar1.jpg',
    streak: '0',
    rank: 'Bronze',
    score: 100,
    level: 'Beginner',
    access_token: 'token1',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    _id: null,
    uid: '2',
    email: 'user2@example.com',
    password: 'password2',
    nick_name: 'User Two',
    age: '30',
    gender: 'Female',
    avatar: 'https://example.com/avatar2.jpg',
    streak: '0',
    rank: 'Silver',
    score: 150,
    level: 'Intermediate',
    access_token: 'token2',
    created_at: new Date(),
    updated_at: new Date(),
  },
];
